apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chain-watcher-hpa
  namespace: erc20
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chain-watcher
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
