apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: indexer-api-hpa
  namespace: erc20
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: indexer-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
